### ISSUE TITLE
Freeswitch not starting

### ISSUE THREAD

**Issue by chaima1995** [ictinnovations/ictfax#46] opened 2020-07-28 09:53 UTC
Hello,

With the provided installation guide, Freeswitch is not starting. I tried googling this problem and I couldn't find any solution. Can you please help me out on this? Here-below is the screenshot on the error that I'm getting from Freeswitch
![freeswitch not starting](https://user-images.githubusercontent.com/67378435/88650306-814fa480-d0c0-11ea-82d2-aa60b43c9d3c.PNG)

**Comment by plochu** [comment] 2020-08-08 21:05
Your problem is quite easy to solve - it is commonly known for years :)
One of options is to edit `/lib/systemd/system/freeswitch.service` and add following:
```
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=1
Nice=-19
```
in `[Service]` section

The bigger problem is that this will not solve whole problem with freeswitch service... it will still not work.
In log journal I can see `freeswitch[26045]: Cannot Initialize [[error near line 8175]: unexpected closing tag </condition>]
`

I really tried but I can't find error and solve this. `/var/log/freeswitch/freeswitch.xml.fsxml` points that the problem is with ICTFAX dialplan - journal points line marked below
```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dialplan>
<!-- ictcore dialplan -->
<include>
  <!-- inbound calls / DID -->
  <context name="ictcore">
    <extension name="application_inbound">
      <condition field="destination_number" expression="^\+?(\d+)$">
        <action application="lua" data="/usr/ictcore/bin/freeswitch/application.lua 0 inbound success" />
        <action application="hangup"/>
```
**and the issue line:**
```
      </condition>
```
```
    </extension>
    <extension name="application_inbound_to">
     <condition field="${sip_to_user}" expression="^\+?(\d+)$">
       <action application="set" data="destination_number=${sip_to_user}">
       <action application="lua" data="/usr/ictcore/bin/freeswitch/application.lua 0 inbound success" />
       <action application="hangup"/>
     </condition>
    </extension>
  </context>
  <!-- handle failed outgoing calls -->
  <context name="ictcore_fail">
    <extension name="app_originate_fail">
      <condition field="${originate_disposition}" expression="^(.*)$">
        <action application="lua" data="/usr/ictcore/bin/freeswitch/spool_failed.lua ${spool_id} ${application_id} $1" />
        <action application="hangup"/>
      </condition>
    </extension>
  </context>
  <!-- external context for outgoing calls, one extension per perfix -->
  <context name="ictcore_gateway">
    <X-PRE-PROCESS cmd="include" data="/usr/ictcore/etc/freeswitch/dialplan/provider/*.xml"/>
    <extension name="catch_invalid">
      <condition field="destination_number" expression=".*">
        <action application="playback" data="sounds/invalid_extension.wav"/>
        <action application="hangup"/>
      </condition>
    </extension>
  </context>
  <!-- internal context for each user -->
  <X-PRE-PROCESS cmd="include" data="/usr/ictcore/etc/freeswitch/dialplan/user/*.xml"/>
</include>
```

**Comment by plochu** [comment] 2020-08-08 22:13
found that this line makes freeswitch fail to start
`<action application="set" data="destination_number=${sip_to_user}">`

**Comment by fizaict** [comment] 2020-08-11 06:03
@chaima1995 can i close this issue? Or still if you have any question feel free to ask

**Comment by plochu** [comment] 2020-08-12 07:29
@fizaict how can I contact you directly? I want to talk about your solution and my company needs :)

**Comment by tahiralmas** [comment] 2020-08-12 12:47
You can submit a ticket using following link in order to contact us for any sales/support query 

https://service.ictinnovations.com/submitticket.php

**Comment by chaima1995** [comment] 2020-08-17 09:51
> 
> 
> @chaima1995 can i close this issue? Or still if you have any question feel free to ask

Thank you all for your help, I tried out your suggestions, now two of the errors are solved but freeswitch still cannot start
![image](https://user-images.githubusercontent.com/67378435/90383121-9bedbb80-e077-11ea-8f7f-d62c0d914370.png)

**Comment by fizaict** [comment] 2020-08-19 06:33
@chaima1995 there is no enough log. I would like to have your system access so i can fix it

**Comment by pkamal992** [comment] 2020-09-14 17:44
Hi @plochu @fizaict 

I really appreciate the great documentation on this product.

I tried the steps to edit "/lib/systemd/system/freeswitch.service" and "/var/log/freeswitch/freeswitch.xml.fsxml"

But **freeswitch** still fails to start. Could you please help me with what next I could try ?

Thanks in advance :)

**Comment by ICTKashif** [comment] 2020-09-14 18:27
Please open `/etc/freeswitch/dialplan/ictcore.xml` file and change following line 
`<action application="set" data="destination_number=${sip_to_user}">`
with 
`<action application="set" data="destination_number=${sip_to_user}"/>`

**/** is mising from the end of 15 no line

**Comment by pkamal992** [comment] 2020-09-15 04:10
Thanks a lot @ICTKashif :) 

I am still left with an error although FreeSwitch is now ACTIVE. When I send FAX it gets stuck in "PROCESSING" and no packets are received on the host configured as Trunk.


`[root@localhost pkamal]# systemctl status freeswitch
● freeswitch.service - FreeSWITCH
   Loaded: loaded (/usr/lib/systemd/system/freeswitch.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2020-09-15 09:38:18 IST; 11s ago
 Main PID: 13006 (freeswitch)
   CGroup: /system.slice/freeswitch.service
           └─13006 /usr/bin/freeswitch -nc -nf

Sep 15 09:38:18 localhost systemd[1]: Started FreeSWITCH.
Sep 15 09:38:18 localhost freeswitch[13006]: ERROR: Failed to set SCHED_FIFO scheduler (Operation not permitted)
[root@localhost pkamal]# `

**Comment by ICTKashif** [comment] 2020-09-15 05:25
edit this file `/etc/freeswitch/autoload_configs/event_socket.conf.xml` and change **listen-ip** with `127.0.0.1` 

and also edit this file `/usr/lib/systemd/system/freeswitch.service` and change User with root like `User=root`

restart the freeswitch and then open ictcore and apache log and send fax from ICTFax Portal. please share the both logs with us in case of issue

`tail -f /usr/ictcore/log/ictcore.log /var/log/httpd/error_log`

**Comment by pkamal992** [comment] 2020-09-16 01:52
Hi @ICTKashif 

Thanks a lot for your help, now I am able to send SIP INVITE out of the fax server. But it seems, the fax server doesn't understand the response. Maybe it is a port issue, could you help me about how to change the SIP listen port from 5070 to 5060 ?

Thanks again for your help :)

**Comment by ICTKashif** [comment] 2020-09-16 06:02
> Hi @ICTKashif
> 
> Thanks a lot for your help, now I am able to send SIP INVITE out of the fax server. But it seems, the fax server doesn't understand the response. Maybe it is a port issue, could you help me about how to change the SIP listen port from 5070 to 5060 ?
> 
> Thanks again for your help :)

Be-default ICTFax used 5060 for outbound sip traffic. I think, your server is behind the NAT, so please first configure the NAT in FreeSwitch add following lines (please use your public IP) in these files `/etc/freeswitch/sip_profiles/external.xml` and `/etc/freeswitch/sip_profiles/ictcore.xml`

    <param name="ext-rtp-ip" value="your-router/public-ip"/>
    <param name="ext-sip-ip" value="your-router/public-ip"/>

**Comment by ICTKashif** [comment] 2020-09-16 06:02
please also share the complete logs from ictcore and freeswitch

**Comment by pkamal992** [comment] 2020-09-16 18:33
[freeswitch.log](https://github.com/ictinnovations/ictfax/files/5234189/freeswitch.log)
[ictcore.log](https://github.com/ictinnovations/ictfax/files/5234190/ictcore.log)

Hi @ICTKashif  

Thanks for your help, I disabled the firewall on linux and also added the static IP of the router in the files you asked.
I am able to receive a response now, but we get a 480 response. Attached the logs as you requested.

Thanks again :)

**Comment by ICTKashif** [comment] 2020-09-16 18:56
after adding/editing trunk on ICTFax portal then you need to restart the freeswitch and please share the complete debug log of freeswitch. 

enable sip debug log 
`sofia global siptrace on`
and also share the following commnad result 
`sofia status`

**Comment by pkamal992** [comment] 2020-09-18 07:19
[freeswitch159_1.log](https://github.com/ictinnovations/ictfax/files/5243974/freeswitch159_1.log)
[freeswitch159.log](https://github.com/ictinnovations/ictfax/files/5243975/freeswitch159.log)

freeswitch@localhost.localdomain> 
freeswitch@localhost.localdomain> sofia status
                     Name          Type                                       Data      State
=================================================================================================
            external-ipv6       profile                   sip:mod_sofia@[::1]:5060      RUNNING (0)
                  ictcore       profile           sip:mod_sofia@10.106.88.161:5070      RUNNING (0)
     ictcore::example.com       gateway                    sip:joeuser@example.com      NOREG
         ictcore::CUBE134       gateway          sip:FreeSWITCH@10.106.88.134:5060      NOREG
                 external       profile           sip:mod_sofia@10.106.88.161:5060      RUNNING (0)
    external::example.com       gateway                    sip:joeuser@example.com      NOREG
=================================================================================================
3 profiles 0 aliases

freeswitch@localhost.localdomain> 

Hi @ICTKashif 

I enabled the SIP and profile traces, attached.

**Comment by pkamal992** [comment] 2020-09-18 07:24
[freeswitch159_1.log](https://github.com/ictinnovations/ictfax/files/5243992/freeswitch159_1.log)
[freeswitch159.log](https://github.com/ictinnovations/ictfax/files/5243993/freeswitch159.log)
[sofia_status.txt](https://github.com/ictinnovations/ictfax/files/5243994/sofia_status.txt)


Hi @ICTKashif  

Attached the logs, the freswitch is responding with "480 Temporarily Unavailable".
My call flow is, ICTFax_1  --> Cisco CUBE --> ICTFax_2

These logs are collected on ICTFAX_2
ICTFAX_1: 10.106.88.158 (DN:1111)
ICTFAX_2: 10.106.88.159 (DN:2222)
Cisco CUBE: 10.106.88.134

Really appreciate your help with this :)

**Comment by ICTKashif** [comment] 2020-09-18 08:53
I hace checked the provided logs, receiving "480 Temporarily Unavailable" from your "Cisco CUBE: 10.106.88.134".
You have added Cisco CUBE as outbound gateway and 2222 is not supported by Cisco CUBE therefore you are receiving 480 error from Cisco.

 and please let me know. why your are trying to dialing ICTFax_1 to ICTFax_2

**Comment by pkamal992** [comment] 2020-09-18 10:16
@ICTKashif 

The 480 message is from ICTFax2  to CUBE

INVITE ---> ICTFax2
100 Trying <--- ICTFax2
480 Temp... <--- ICTFax2

I am trying to setup a fax call flow  to test T.38 fax calling through the cisco router.


**recv 1212 bytes** from udp/[10.106.88.134]:53406 at 12:44:41.540839:
   ------------------------------------------------------------------------
   **INVITE sip:**2222@10.106.88.159:5060 SIP/2.0

**send 656 bytes** to udp/[10.106.88.134]:5060 at 12:44:41.543214:
   ------------------------------------------------------------------------
   **SIP/2.0 480** Temporarily Unavailable

**Comment by mr2017x** [comment] 2020-10-04 21:22
Take this file

 vim /etc/freeswitch/dialplan/ictcore.xml

running at same problem, still dont know why my extension is not logging in but changing the file under var log is ...interesting...also wondering why demo show more options than my installation?

**Closed** 2020-10-28 07:38 UTC
